import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { SessionWrapper } from './components/SessionWrapper';
import Header from "./components/header/Header";

const monserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Spotify Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={monserrat.className}>
        <div>
            <main>
              <SessionWrapper>
                <Header />
                  {children}
              </SessionWrapper>
            </main>
        </div>
      </body>
    </html>
  );
}
